In [12]:
#create model class
import torch
import torch.nn as nn

class Model(nn.Module): #sup imp
  def __init__(self, num_features):
    super().__init__() #child class calling parent using super
    self.linear1 = nn.Linear(num_features,3)
    self.relu = nn.ReLU()
    self.linear2 = nn.Linear(3,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self,featuers):
    out = self.linear1(features)
    out = self.relu(out)
    out = self.linear2(out)
    out = self.sigmoid(out)

    return out

In [13]:
#create dataset
features = torch.rand(10,5) # 5 features
#create model
model = Model(features.shape[1])
#call model for forward pass
# model.forward(features)
model(features) # recommanded this one

tensor([[0.5446],
        [0.5117],
        [0.5223],
        [0.5112],
        [0.5440],
        [0.5599],
        [0.5448],
        [0.5130],
        [0.5416],
        [0.5604]], grad_fn=<SigmoidBackward0>)

In [18]:
#shoe model weights
model.linear1.weight


Parameter containing:
tensor([[ 0.2553,  0.2885, -0.1674,  0.3069,  0.0824],
        [-0.2640,  0.2303, -0.2384, -0.2209,  0.0021],
        [ 0.2615, -0.1714,  0.4291,  0.0182,  0.1172]], requires_grad=True)

In [17]:
model.linear2.weight

Parameter containing:
tensor([[0.4826, 0.4328, 0.3475]], requires_grad=True)

In [19]:
#shoe model bias
model.linear.bias

AttributeError: 'Model' object has no attribute 'linear'

In [9]:
!pip install torchinfo

In [20]:
from torchinfo import summary
summary(model, input_size = (10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00