In [58]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [59]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [60]:
df.shape

(569, 33)

In [61]:
df.drop(columns=['id','Unnamed: 32'],inplace=True)

In [62]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [63]:
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)

In [64]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [65]:
X_train

array([[-0.74257749, -0.28050404, -0.67221407, ...,  0.4040442 ,
        -0.37065718,  0.51643019],
       [-0.70582579, -0.42378315, -0.69234522, ..., -0.22390273,
        -0.68654105, -0.35766328],
       [-0.38354169, -1.44984649, -0.44584141, ..., -0.95609504,
        -0.9798618 , -0.84410525],
       ...,
       [ 0.2497183 ,  2.40713483,  0.16302299, ..., -0.76910296,
         0.62385636, -1.27739679],
       [-1.36000597, -0.24815069, -1.35256458, ..., -1.00466039,
        -0.72819607, -0.13870662],
       [ 0.59461883,  0.90039318,  0.66794495, ...,  1.69087141,
         3.38523686,  0.71516657]])

In [66]:
X_test

array([[-1.29470104, -0.20886448, -1.28395435, ..., -0.77142296,
         0.52145444,  0.08544954],
       [-1.05638043,  0.18399761, -0.99020398, ..., -0.83700166,
        -0.8514255 ,  0.37546601],
       [ 0.54373186, -0.76811522,  0.55701824, ...,  0.14884409,
         0.4850063 ,  0.33733635],
       ...,
       [-0.80194561, -1.03387487, -0.78930338, ..., -0.81225498,
        -1.8442034 , -0.54831156],
       [-1.48326551, -1.15404445, -1.49471511, ..., -1.57120463,
         0.20383494, -0.33051034],
       [ 0.80099373,  1.79242121,  0.75832968, ...,  0.61903095,
         0.23681182,  0.39510856]])

In [67]:
y_train

469    B
530    B
287    B
178    B
451    M
      ..
554    B
432    M
414    M
359    B
370    M
Name: diagnosis, Length: 455, dtype: object

In [68]:
## Label Encoding on string data

In [69]:
encoder = LabelEncoder()
encoder.fit(list(set(y_train) | set(y_test)))

y_train = encoder.transform(y_train)
y_test = encoder.transform(y_test)


In [70]:
y_train

array([0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1,

In [71]:
y_test

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 1])

In [72]:
## Numpy to Pytorch tensors

In [73]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [74]:
X_train_tensor.shape

torch.Size([455, 30])

In [75]:
X_test_tensor.shape

torch.Size([114, 30])

In [76]:
X_train_tensor

tensor([[-0.7426, -0.2805, -0.6722,  ...,  0.4040, -0.3707,  0.5164],
        [-0.7058, -0.4238, -0.6923,  ..., -0.2239, -0.6865, -0.3577],
        [-0.3835, -1.4498, -0.4458,  ..., -0.9561, -0.9799, -0.8441],
        ...,
        [ 0.2497,  2.4071,  0.1630,  ..., -0.7691,  0.6239, -1.2774],
        [-1.3600, -0.2482, -1.3526,  ..., -1.0047, -0.7282, -0.1387],
        [ 0.5946,  0.9004,  0.6679,  ...,  1.6909,  3.3852,  0.7152]],
       dtype=torch.float64)

In [77]:
## Ddefining the model

In [78]:
class MySimpleNN():
  def __init__(self,X):

    self.weights = torch.rand(X.shape[1],1,dtype=torch.float64,requires_grad=True)
    self.bias = torch.zeros(1,dtype = torch.float64,requires_grad=True)

  def forward(self,X):
    z = torch.matmul(X,self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self, y_pred, y):
    # Clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

    # Calculate loss
    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss

In [79]:
#Important Parameters
learning_rate = 0.1
epochs=25

In [80]:
# Training Pipline

In [81]:
#create model
model = MySimpleNN(X_train_tensor)
model.weights

tensor([[1.9555e-01],
        [5.9278e-01],
        [1.2610e-02],
        [8.8262e-01],
        [8.8847e-01],
        [9.4593e-01],
        [3.7394e-01],
        [4.6814e-01],
        [1.9223e-01],
        [8.4154e-01],
        [2.3491e-01],
        [8.8338e-01],
        [9.6444e-01],
        [6.3983e-01],
        [7.5006e-01],
        [7.8513e-02],
        [2.1091e-04],
        [8.4113e-01],
        [5.0963e-01],
        [1.6555e-01],
        [9.6530e-02],
        [9.6933e-01],
        [3.7230e-01],
        [7.3448e-01],
        [2.7743e-01],
        [3.8470e-02],
        [6.5785e-01],
        [5.2852e-01],
        [5.5199e-02],
        [7.6463e-01]], dtype=torch.float64, requires_grad=True)

In [82]:
model.bias

tensor([0.], dtype=torch.float64, requires_grad=True)

In [83]:
# create model
model = MySimpleNN(X_train_tensor)

# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model.forward(X_train_tensor)

  # loss calculate
  loss = model.loss_function(y_pred, y_train_tensor)

  # backward pass
  loss.backward()

  # parameters update
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  # zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 4.0540509399988025
Epoch: 2, Loss: 3.945250973440988
Epoch: 3, Loss: 3.829681869195197
Epoch: 4, Loss: 3.7115774971822404
Epoch: 5, Loss: 3.589191463947813
Epoch: 6, Loss: 3.461668232105259
Epoch: 7, Loss: 3.332754168564657
Epoch: 8, Loss: 3.200497051354699
Epoch: 9, Loss: 3.0600730035910972
Epoch: 10, Loss: 2.9127165418104153
Epoch: 11, Loss: 2.755081987121772
Epoch: 12, Loss: 2.5959613668143855
Epoch: 13, Loss: 2.4400773476262234
Epoch: 14, Loss: 2.2833940597903286
Epoch: 15, Loss: 2.1272113578710123
Epoch: 16, Loss: 1.9753130631679916
Epoch: 17, Loss: 1.8259034901112334
Epoch: 18, Loss: 1.6827901659377469
Epoch: 19, Loss: 1.5423658082796738
Epoch: 20, Loss: 1.4151291738559377
Epoch: 21, Loss: 1.3024802249745853
Epoch: 22, Loss: 1.203839726975894
Epoch: 23, Loss: 1.119529839669892
Epoch: 24, Loss: 1.050663501834871
Epoch: 25, Loss: 0.9956399655428164


In [84]:
model.weights

tensor([[ 6.4668e-02],
        [ 3.8892e-01],
        [-4.4497e-01],
        [ 5.0825e-01],
        [-4.3943e-02],
        [-5.7614e-04],
        [-5.6559e-01],
        [-1.6435e-01],
        [-2.8674e-01],
        [ 6.2603e-01],
        [ 2.0947e-01],
        [-1.2306e-01],
        [ 3.2903e-01],
        [ 4.6278e-01],
        [ 6.3980e-02],
        [ 2.7058e-01],
        [ 2.7751e-01],
        [ 3.3843e-01],
        [ 4.7568e-01],
        [ 2.3855e-01],
        [ 4.6904e-01],
        [ 2.2545e-01],
        [ 2.5449e-01],
        [-3.5017e-01],
        [ 2.1431e-01],
        [ 2.0734e-01],
        [-2.1302e-01],
        [-6.3915e-01],
        [-2.4374e-01],
        [ 9.8026e-02]], dtype=torch.float64, requires_grad=True)

In [85]:
model.bias

tensor([-0.0832], dtype=torch.float64, requires_grad=True)

In [86]:
#Evaluation

In [87]:
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)

In [88]:
print(y_pred)

tensor([[0.3356],
        [0.8945],
        [0.1935],
        [0.1553],
        [0.9334],
        [0.4851],
        [0.2718],
        [0.5505],
        [0.2684],
        [0.5940],
        [0.1032],
        [0.3871],
        [0.3418],
        [0.2962],
        [0.2986],
        [0.3093],
        [0.4698],
        [0.5834],
        [0.6971],
        [0.3908],
        [0.2660],
        [0.7466],
        [0.2211],
        [0.3726],
        [0.9015],
        [0.9755],
        [0.5489],
        [0.1110],
        [0.2186],
        [0.9683],
        [0.8283],
        [0.3613],
        [0.1066],
        [0.1668],
        [0.5463],
        [0.9998],
        [0.3674],
        [0.3527],
        [0.5666],
        [0.1687],
        [0.3229],
        [0.9548],
        [0.4376],
        [0.1252],
        [0.1402],
        [0.3109],
        [0.5489],
        [0.6458],
        [0.2010],
        [0.2386],
        [0.6917],
        [0.7494],
        [0.6904],
        [0.9090],
        [0.2919],
        [0

In [90]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.6163434982299805
