In [212]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [213]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [214]:
df.shape

(569, 33)

In [215]:
df.drop(columns=['id','Unnamed: 32'],inplace=True)

In [216]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [217]:
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)

In [218]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [219]:
X_train

array([[ 0.12438631,  0.00324095,  0.10279089, ..., -0.28017878,
        -0.70164218, -0.52145735],
       [ 2.09248199,  0.69839238,  2.04084679, ...,  1.62774657,
        -1.3616154 , -0.71673192],
       [-0.52511327, -0.29761147, -0.54417479, ..., -0.39633053,
         0.49787119, -0.51752941],
       ...,
       [ 0.2783625 ,  1.46191935,  0.25499423, ...,  0.58010333,
        -0.40778549,  0.58678196],
       [-0.34594097,  0.46591551, -0.36883653, ..., -0.88644536,
        -0.67434402, -0.13539728],
       [ 0.57231705, -0.32952006,  0.62028225, ...,  1.09329668,
         2.18714571,  2.209581  ]])

In [220]:
X_test

array([[-0.38793448, -1.63093469, -0.43986476, ..., -0.4881891 ,
        -0.2134868 ,  0.60137144],
       [ 0.57231705,  0.30865174,  0.66492857, ...,  1.4106263 ,
         1.28148903,  1.69894921],
       [ 3.67703699,  0.57987476,  3.66840786, ...,  2.34439527,
        -0.08341909, -0.17411551],
       ...,
       [ 1.18262268,  0.28585989,  1.18039056, ...,  0.55581016,
         0.2666397 , -0.29700382],
       [-0.1051782 ,  0.34283952, -0.06158872, ...,  0.62565304,
         0.46254416,  1.74945126],
       [ 0.21677202,  0.88528555,  0.35240437, ...,  0.88528636,
         0.1478124 ,  0.17322633]])

In [221]:
y_train

448    B
564    M
367    B
513    B
41     M
      ..
150    B
76     B
353    M
407    B
34     M
Name: diagnosis, Length: 455, dtype: object

In [222]:
## Label Encoding on string data

In [223]:
encoder = LabelEncoder()
encoder.fit(list(set(y_train) | set(y_test)))

y_train = encoder.transform(y_train)
y_test = encoder.transform(y_test)


In [224]:
y_train

array([0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1,

In [225]:
y_test

array([0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 1, 1, 1])

In [226]:
## Numpy to Pytorch tensors

In [227]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [228]:
X_train_tensor.shape

torch.Size([455, 30])

In [229]:
X_test_tensor.shape

torch.Size([114, 30])

In [230]:
X_train_tensor

tensor([[ 0.1244,  0.0032,  0.1028,  ..., -0.2802, -0.7016, -0.5215],
        [ 2.0925,  0.6984,  2.0408,  ...,  1.6277, -1.3616, -0.7167],
        [-0.5251, -0.2976, -0.5442,  ..., -0.3963,  0.4979, -0.5175],
        ...,
        [ 0.2784,  1.4619,  0.2550,  ...,  0.5801, -0.4078,  0.5868],
        [-0.3459,  0.4659, -0.3688,  ..., -0.8864, -0.6743, -0.1354],
        [ 0.5723, -0.3295,  0.6203,  ...,  1.0933,  2.1871,  2.2096]],
       dtype=torch.float64)

In [231]:
## Ddefining the model

In [232]:
import torch
import torch.nn as nn
class MySimpleNN(nn.Module):

  def __init__(self,num_features):
    super().__init__()
    self.linear = nn.Linear(num_features,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self,features):
    out = self.linear(features)
    out = self.sigmoid(out)
    return out



In [233]:
#Important Parameters
learning_rate = 0.1
epochs=25

In [234]:
loss_function = nn.BCELoss()

In [235]:
 # Training Pipline

In [236]:
# create model
model = MySimpleNN(X_train_tensor.shape[1])

#define optimizer
optimizer = torch.optim.SGD(model.parameters(), lr = learning_rate)

# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model(X_train_tensor.float())

  # loss calculate
  loss = loss_function(y_pred, y_train_tensor.view(-1,1).float())

  # clear gradients
  optimizer.zero_grad()

  # backward pass
  loss.backward()

  # parameters update
  optimizer.step()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.787846565246582
Epoch: 2, Loss: 0.570622980594635
Epoch: 3, Loss: 0.4617716372013092
Epoch: 4, Loss: 0.39900726079940796
Epoch: 5, Loss: 0.35728541016578674
Epoch: 6, Loss: 0.32704582810401917
Epoch: 7, Loss: 0.3038685917854309
Epoch: 8, Loss: 0.28539350628852844
Epoch: 9, Loss: 0.27023109793663025
Epoch: 10, Loss: 0.257503867149353
Epoch: 11, Loss: 0.2466275691986084
Epoch: 12, Loss: 0.23719646036624908
Epoch: 13, Loss: 0.22891899943351746
Epoch: 14, Loss: 0.2215796560049057
Epoch: 15, Loss: 0.2150154560804367
Epoch: 16, Loss: 0.2091003805398941
Epoch: 17, Loss: 0.20373542606830597
Epoch: 18, Loss: 0.19884146749973297
Epoch: 19, Loss: 0.19435453414916992
Epoch: 20, Loss: 0.1902221292257309
Epoch: 21, Loss: 0.1864008605480194
Epoch: 22, Loss: 0.18285438418388367
Epoch: 23, Loss: 0.17955198884010315
Epoch: 24, Loss: 0.176467627286911
Epoch: 25, Loss: 0.17357893288135529


In [237]:
model.linear.weight

Parameter containing:
tensor([[ 0.2339,  0.2677,  0.4365,  0.2873, -0.0168,  0.1895,  0.2398,  0.3370,
          0.0413, -0.1178,  0.1254,  0.0442,  0.2136,  0.0249, -0.0605, -0.0091,
         -0.0234, -0.0363, -0.0254,  0.0294,  0.1216,  0.0842,  0.1963,  0.3557,
          0.2350,  0.0684,  0.2853,  0.1263,  0.1480,  0.2062]],
       requires_grad=True)

In [238]:
model.linear.bias

Parameter containing:
tensor([-0.1355], requires_grad=True)

In [239]:
#Evaluation

In [240]:
with torch.no_grad():
  y_pred = model.forward(X_test_tensor.float())

In [241]:
print(y_pred)

tensor([[0.0729],
        [0.9774],
        [1.0000],
        [0.9937],
        [0.6988],
        [0.0407],
        [0.1704],
        [0.5828],
        [0.9978],
        [0.8447],
        [0.0684],
        [0.9999],
        [0.0192],
        [0.1131],
        [0.0272],
        [0.9320],
        [0.8153],
        [0.0574],
        [0.0457],
        [0.9860],
        [0.0224],
        [0.9319],
        [0.3024],
        [0.4007],
        [0.2894],
        [0.1438],
        [0.0753],
        [0.9490],
        [0.3467],
        [0.8739],
        [0.0318],
        [0.1006],
        [0.5766],
        [0.9842],
        [0.1655],
        [0.9913],
        [0.0582],
        [0.0215],
        [0.0517],
        [0.1327],
        [0.0492],
        [0.6268],
        [0.3179],
        [0.1843],
        [0.2454],
        [0.0631],
        [0.0503],
        [0.5873],
        [0.9997],
        [0.1212],
        [0.9824],
        [0.6720],
        [0.0838],
        [0.1075],
        [0.1058],
        [0

In [242]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor.float())
  y_pred = (y_pred > 0.5).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.5340104699134827
