In [5]:
#create model class
import torch
import torch.nn as nn

class Model(nn.Module): #sup imp
  def __init__(self, num_features):
    super().__init__() #child class calling parent using super
    self.linear = nn.Linear(num_features,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self,featuers):
    out = self.linear(features)
    out = self.sigmoid(out)

    return out

In [6]:
#create dataset
features = torch.rand(10,5) # 5 features
#create model
model = Model(features.shape[1])
#call model for forward pass
# model.forward(features)
model(features) # recommanded this one

tensor([[0.3886],
        [0.3574],
        [0.3583],
        [0.3598],
        [0.3210],
        [0.3803],
        [0.3802],
        [0.3576],
        [0.3983],
        [0.3609]], grad_fn=<SigmoidBackward0>)

In [7]:
#shoe model weights
model.linear.weight

Parameter containing:
tensor([[-0.2487, -0.2716,  0.0429, -0.4344,  0.1860]], requires_grad=True)

In [8]:
#shoe model bias
model.linear.bias

Parameter containing:
tensor([-0.2518], requires_grad=True)

In [9]:
!pip install torchinfo

In [11]:
from torchinfo import summary
summary(model, input_size = (10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00